apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
         environment: production
         app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: itzg/minecraft-server:latest  # Or specific version if needed
          env:
            - name: EULA
              value: "TRUE"
            - name: MODE
              value: "survival"
            - name: TYPE
              value: "VANILLA"
            - name: INIT_MEMORY
              value: 2G
            - name: MAX_MEMORY
              value: 4G
            - name: ALLOW_FLIGHT
              value: "FALSE"
            - name: RCON_PASSWORD
              value: "ohPen_DeeDar.0604#"
          ports:
            - name: minecraft
              containerPort: 25565  # Expose port 25565
            - name: minecraft-rcon
              containerPort: 25575  # Expose port 25575
            - name: metrics
              containerPort: 19565  # Expose port 19565

          resources:
            requests:
              cpu: 1  # Adjust based on expected workload
              memory: "4Gi"  # Adjust based on expected workload
            limits:
              cpu: 2  # Adjust based on expected workload
              memory: "6Gi"  # Adjust based on expected workload
          readinessProbe:
              exec:
                command:
                - mcstatus
                - 127.0.0.1
                - ping
              initialDelaySeconds: 30
              periodSeconds: 30
          livenessProbe:
            exec:
              command:
              - mcstatus
              - 127.0.0.1
              - ping
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
          - name: minecraft-data
            mountPath: /data
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data
            spec:
                storageClassName: nfs-client
                accessModes:
                    - ReadWriteMany
                resources:
                    requests:
                    storage: 111Gi
