---
apiVersion: v1
kind: Service
metadata: 
  name: server
  namespace: minecraft
  labels: 
    app:  server
spec:
  selector:
    app: server               # name of Pod we want to talk to
  type: LoadBalancer          # request external IP / routing
  ports:
    - name: game
      protocol: TCP           
      port: 25565             # port exposed to Cluster
      targetPort: 25565       # matches 'containerPort'
      nodePort: 30565         # the external IP address port to connect on  
    - name: console
      protocol: TCP           
      port: 25575             # port exposed to Cluster
      targetPort: 25575       # matches 'containerPort'
      nodePort: 30575         # the external IP address port to connect on  
    - name: metrics
      protocol: TCP           
      port: 19565             # port exposed to Cluster
      targetPort: 19565       # matches 'containerPort'
      nodePort: 30585         # the external IP address port to connect on

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: server
  serviceName: "server"
  replicas: 1
# ---------  
  template:
    metadata:
      labels:
         environment: production
         app: server
    spec:
      containers:
        - name: server
          image: itzg/minecraft-server:latest  # Or specific version if needed
          env:
          - name: OVERRIDE_SERVER_PROPERTIES
            value: "FALSE"
          - name: EULA
            value: "TRUE"
          - name: ENABLE_AUTOSTOP
            value: "FALSE"
          - name: ENABLE_AUTOPAUSE
            value: "FALSE"
          - name: AUTOPAUSE_TIMEOUT_INIT
            value: "7200"
          - name: AUTOPAUSE_TIMEOUT_EST
            value: "7200"
          - name: MODE
            value: "survival"
          - name: TYPE
            value: "CURSEFORGE"
#            value: "VANILLA"
          - name: CF_SERVER_MOD
            value: "/modpacks/your-modpack.zip"
          - name: INIT_MEMORY
            value: 2G
          - name: MAX_MEMORY
            value: 4G
          - name: ALLOW_FLIGHT
            value: "FALSE"
          - name: RCON_PASSWORD
            valueFrom:
              secretKeyRef:
                name: minecraft-secret
                key: rcon-pass
          - name: MOTD
            value: "Welcome To\n §l§cDiggyDig II§r \nMinecraft Server"
          - name: DIFFICULTY
            value: "normal"
          - name: MAX_PLAYERS
            value: "11"
          - name: MAX_WORLD_SIZE
            value: "11111"
          - name: ALLOW_NETHER
            value: "TRUE"
          - name: ANNOUNCE_PLAYER_ACHIEVEMENTS
            value: "TRUE"
          - name: FORCE_GAMEMODE
            value: "TRUE"
          - name: GENERATE_STRUCTURES
            value: "TRUE"
          - name: SPAWN_ANIMALS
            value: "TRUE"
          - name: SPAWN_MONSTERS
            value: "TRUE"
          - name: SPAWN_NPCS
            value: "TRUE"
          - name: VIEW_DISTANCE
            value: "11"
          - name: PVP
            value: "false"
          - name: SEED
            valueFrom:
              secretKeyRef: 
                name: minecraft-secret
                key: levelSeed
          - name: SERVER_NAME
            valueFrom:
              secretKeyRef: 
                name: minecraft-secret
                key: worldSaveName
          volumeMounts:
          - mountPath: /data
            name: mc-data-vol
#            subPath: minecraft
# ---------------------          
          ports:
            - name: game
              containerPort: 25565  # Expose port 25565 to Service
            - name: console
              containerPort: 25575  # Expose port 25575 to Service
            - name: metrics
              containerPort: 19565  # Expose port 19565 to Service
          resources:
            requests:
              cpu: 1  # Adjust based on expected workload
              memory: "4Gi"  # Adjust based on expected workload
            limits:
              cpu: 2  # Adjust based on expected workload
              memory: "6Gi"  # Adjust based on expected workload
 #         readinessProbe:
 #             exec:
 #               command:
 #               - mcstatus
 #               - 127.0.0.1
 #               - ping
 #             initialDelaySeconds: 30
 #             periodSeconds: 30
 #         livenessProbe:
 #           exec:
 #             command:
 #             - mcstatus
 #             - 127.0.0.1
 #             - ping
 #           initialDelaySeconds: 30
 #           periodSeconds: 30
# ---------------------
      volumes:
        - name: mc-data-vol
          persistentVolumeClaim:
            claimName: nfs-mount
# ---
