apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
         environment: production
         app: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: itzg/minecraft-server:latest  # Or specific version if needed
          env:
            - name: EULA
              value: "TRUE"
            - name: MODE
              value: "survival"
            - name: TYPE
              value: "VANILLA"
            - name: INIT_MEMORY
              value: 2G
            - name: MAX_MEMORY
              value: 4G
            - name: ALLOW_FLIGHT
              value: "FALSE"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: minecraft-secret
                  key: rcon-pass
          ports:
            - name: mc-server
              containerPort: 25565  # Expose port 25565 to Service
            - name: mc-rcon
              containerPort: 25575  # Expose port 25575 to Service
            - name: mc-metrics
              containerPort: 19565  # Expose port 19565 to Service
          resources:
            requests:
              cpu: 1  # Adjust based on expected workload
              memory: "4Gi"  # Adjust based on expected workload
            limits:
              cpu: 2  # Adjust based on expected workload
              memory: "6Gi"  # Adjust based on expected workload
          readinessProbe:
              exec:
                command:
                - mcstatus
                - 127.0.0.1
                - ping
              initialDelaySeconds: 30
              periodSeconds: 30
          livenessProbe:
            exec:
              command:
              - mcstatus
              - 127.0.0.1
              - ping
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: minecraft-data-vc
          persistentVolumeClaim:
            claimName: minecraft-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-data
spec:
  storageClassName: nfs-client.wolfstar
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 11Gi
---
apiVersion: v1
kind: Service
metadata: 
  name: minecraft-service
  namespace: minecraft
spec:
  selector:
    app: minecraft-server   # name of Pod we want to talk to
  type: LoadBalancer          # request external IP / routing
  ports:
    - name: game-service
      protocol: TCP           
      port: 25565             # port exposed to Cluster
      targetPort: mc-server       # matches 'containerPort'
      nodePort: 30565         # the external IP address port to connect on  
    - name: game-console
      protocol: TCP           
      port: 25575             # port exposed to Cluster
      targetPort: mc-rcon       # matches 'containerPort'
      nodePort: 30575         # the external IP address port to connect on  
    - name: server-metrics
      protocol: TCP           
      port: 19565             # port exposed to Cluster
      targetPort: mc-metrics       # matches 'containerPort'
      nodePort: 30585         # the external IP address port to connect on
