apiVersion: v1
kind: Service
metadata:
    name: diggydig-mc-metallb
    namespace: minecraft
spec:
    selector:
        app: diggydig-mc-minecraft
    ports:
      - name: game
        port: 25565
        targetPort: 25565
        protocol: TCP
      - name: rcon
        port: 25575
        targetPort: 25575
        protocol: TCP
    type: LoadBalancer
