apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mount
  namespace: minecraft
spec:
  capacity:
    storage:  111Gi    # the max amount available for use by all pods
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-client
  mountOptions:
    - hard
    - nfsvers=4.0
  nfs:
    path: /mount/raidset/shares/nfs/pv-nfs-mount
    server: 192.168.0.112
