---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-mount
  namespace: minecraft
spec:
  storageClassName: nfs-client
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 11Gi
# ---
